welcome = "my basic program!"
print("Welcome to {}".format(welcome))
name=str(input("Adınızı giriniz: "))
surname=str(input("Soyadınızı girininiz: "))
gender=str(input("Cinsiyetiniz(E-K): "))
age=int(input("Yaş: "))
height=float(input("Boyunuz(m): "))
weight=float(input("Kilonuz: "))
print(name,"~",surname,"~",gender,"~",age,"~",height,"~",weight)
print(type(name),"\t")
print(type(surname))
print(type(gender))
print(type(age))
print(type(height))
print(type(weight))